function cfg = config_default()
%CONFIG_DEFAULT SI units. World and body are right handed, z UP.
% World: local Cartesian. Body: x forward, y left, z up (FLU).
cfg.N = 3;
cfg.mode = 'paper';                % 'paper' or 'geometric'
cfg.T = 60;
cfg.dt = 0.002;                    % fixed-step ode4 integration
cfg.Ts = 0.01;                     % formation + autopilot, 100 Hz
cfg.logTs = 0.02;
cfg.visualTs = 0.05;
cfg.visualize = true;
cfg.pacing = false;                % true requests 1 simulated s/wall-clock s
cfg.receiver = [4;-3;15];           % m, fixed throughout simulation
cfg.radius = 0.8;                  % circumradius, NOT triangle side length
cfg.path.center = [0;0;3];
cfg.path.amplitude = [2.5;1.5;0.35];
cfg.path.period = 40;
cfg.path.ramp = 5;                 % smooth ramp from rest
cfg.path.type = 'figure8';         % 'figure8', 'circle', 'hover'
cfg.frameSeed = [1;0;0];           % projects onto desired formation plane
cfg.yaw = 0;                      % drone body heading; not formation rotation
cfg.initial.centroidError = [0.15;-0.10;0.10];
cfg.initial.formationRotation = [0;12*pi/180;0]; % world rotation vector
cfg.initial.individualError = 0;  % m; deterministic zero-mean offsets
cfg.control.Kp = [2.5;2.5;3.5];
cfg.control.Kd = [2.8;2.8;3.2];
cfg.control.beta = 1.3;            % formation SO(3) feedback
cfg.control.kc = 0.9;              % centroid position feedback, 1/s
cfg.control.kv = 0.45;             % dimensioned distance feedback gain
cfg.control.ka = 3.2;              % acceleration backstepping gain
cfg.control.kq = 1.0;              % weight on -J'*q
cfg.control.kPlane = 4;
cfg.control.dPlane = 3;
cfg.control.maxHorizontalAccel = 4;
cfg.control.maxVerticalAccel = 4;
cfg.control.maxTilt = 35*pi/180;
cfg.vehicle.mass = 1.0;
cfg.vehicle.g = 9.81;
cfg.vehicle.I = diag([0.015 0.015 0.025]);
cfg.vehicle.arm = 0.225;           % center to rotor distance
cfg.vehicle.kT = 1.8e-5;          % N/(rad/s)^2
cfg.vehicle.kQ = 2.7e-7;          % Nm/(rad/s)^2
cfg.vehicle.motorTau = 0.025;
cfg.vehicle.omegaMax = 620;        % rad/s
cfg.vehicle.drag = [0.12;0.12;0.18]; % N/(m/s), world-axis linear drag
cfg.vehicle.angularDrag = [0.002;0.002;0.003];
cfg.vehicle.KR = [2.2;2.2;1.2];
cfg.vehicle.Kw = [0.32;0.32;0.28];
cfg.vehicle.bodyRadius = 0.27;     % conservative horizontal rotor envelope
cfg.wind.enabled = false;
cfg.wind.velocity = [0.8;0.3;0];  % steady air velocity when enabled
cfg.wind.gust = [0.3;0.2;0.1];
cfg.rf.frequency = 138e6;
cfg.rf.c = 299792458;
cfg.rf.powerPerDrone = 0.1;        % W, isotropic, coherent narrowband sources
cfg.rf.noisePower = 1e-13;         % W (-100 dBm)
cfg.rf.phaseOffsets = [];         % rad, one per REAL drone; [] means zero
cfg.rf.enabled = true;
end
